"""create poker tracking tables

Revision ID: f97ad54de52b
Revises: 
Create Date: 2026-06-12 22:27:48.963936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97ad54de52b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('small_blind', sa.Float(), nullable=False),
    sa.Column('big_blind', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_table('opponent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('total_hands_observed', sa.Integer(), nullable=True),
    sa.Column('vpip_count', sa.Integer(), nullable=True),
    sa.Column('pfr_count', sa.Integer(), nullable=True),
    sa.Column('three_bet_count', sa.Integer(), nullable=True),
    sa.Column('agg_actions', sa.Integer(), nullable=True),
    sa.Column('pass_actions', sa.Integer(), nullable=True),
    sa.Column('inferred_style', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opponent_profiles_id'), 'opponent_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_opponent_profiles_player_name'), 'opponent_profiles', ['player_name'], unique=True)
    op.create_table('hand_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('hole_cards', sa.JSON(), nullable=False),
    sa.Column('community_cards', sa.JSON(), nullable=False),
    sa.Column('pot_size', sa.Float(), nullable=False),
    sa.Column('stack_size', sa.Float(), nullable=False),
    sa.Column('num_active_players', sa.Integer(), nullable=False),
    sa.Column('calculated_equity', sa.Float(), nullable=False),
    sa.Column('required_equity', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('ai_explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hand_histories_id'), 'hand_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hand_histories_id'), table_name='hand_histories')
    op.drop_table('hand_histories')
    op.drop_index(op.f('ix_opponent_profiles_player_name'), table_name='opponent_profiles')
    op.drop_index(op.f('ix_opponent_profiles_id'), table_name='opponent_profiles')
    op.drop_table('opponent_profiles')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
